-- Implementation task2 task1
-- Timothy Mah
-- 8750634
-- txamah001@mymail.sim.edu.sg

SPOOL It2Solution1.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

-- qn (a) (i)
explain plan set STATEMENT_ID='1ai' for
SELECT L_DISCOUNT FROM LINEITEM WHERE L_SHIPDATE = (SELECT MAX(L_SHIPDATE) FROM LINEITEM);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1ai','SERIAL'));
-- qn (a) (ii)
explain plan set STATEMENT_ID='1aii' for
SELECT COUNT(*) FROM LINEITEM WHERE L_SHIPMODE = 'AIR' AND EXTRACT(YEAR FROM L_SHIPDATE) = 1998;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1aii','SERIAL'));
-- qn (a) (iii)
explain plan set STATEMENT_ID='1aiii' for
SELECT L_ORDERKEY, L_LINENUMBER FROM LINEITEM WHERE L_DISCOUNT = (SELECT MAX(L_DISCOUNT) FROM LINEITEM);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1aiii','SERIAL'));
-- qn (a) (iv)
explain plan set STATEMENT_ID='1aiv' for
SELECT  L_LINESTATUS, COUNT(*) FROM LINEITEM GROUP BY L_LINESTATUS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1aiv','SERIAL'));
-- qn (a) (v)
explain plan set STATEMENT_ID='1av' for
SELECT L_ORDERKEY, L_LINENUMBER, L_LINESTATUS, L_SHIPDATE, L_SHIPMODE FROM LINEITEM WHERE L_ORDERKEY IN(1795718, 1799046, 1794626);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1av','SERIAL'));


-- qn (b) (i)
CREATE INDEX onebi_idx ON LINEITEM(L_SHIPDATE, L_DISCOUNT);

explain plan set STATEMENT_ID='1bi-idx' for
SELECT L_DISCOUNT FROM LINEITEM WHERE L_SHIPDATE = (SELECT MAX(L_SHIPDATE) FROM LINEITEM);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1bi-idx','SERIAL'));

DROP INDEX onebi_idx;

-- qn (b) (ii)
CREATE INDEX onebii_idx ON LINEITEM(L_SHIPDATE, L_SHIPMODE);

explain plan set STATEMENT_ID='1bii-idx' for
SELECT COUNT(*) FROM LINEITEM WHERE L_SHIPMODE = 'AIR' AND EXTRACT(YEAR FROM L_SHIPDATE) = 1998;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1bii-idx','SERIAL'));

DROP INDEX onebii_idx;

-- qn (b) (iii)
CREATE INDEX onebiii_idx ON LINEITEM(L_ORDERKEY, L_LINENUMBER, L_DISCOUNT);

explain plan set STATEMENT_ID='1biii-idx' for
SELECT L_ORDERKEY, L_LINENUMBER FROM LINEITEM WHERE L_DISCOUNT = (SELECT MAX(L_DISCOUNT) FROM LINEITEM);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1biii-idx','SERIAL'));

DROP INDEX onebiii_idx;

-- qn (b) (iv)
CREATE INDEX onebiv_idx ON LINEITEM(L_LINESTATUS);

explain plan set STATEMENT_ID='1biv-idx' for
SELECT  L_LINESTATUS, COUNT(*) FROM LINEITEM GROUP BY L_LINESTATUS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1biv-idx','SERIAL'));

DROP INDEX onebiv_idx;

-- qn (b) (v)
CREATE INDEX onebv_idx ON LINEITEM(L_ORDERKEY, L_LINENUMBER, L_LINESTATUS, L_SHIPDATE, L_SHIPMODE);

explain plan set STATEMENT_ID='1bv-idx' for
SELECT L_ORDERKEY, L_LINENUMBER, L_LINESTATUS, L_SHIPDATE, L_SHIPMODE FROM LINEITEM WHERE L_ORDERKEY IN(1795718, 1799046, 1794626);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','1bv-idx','SERIAL'));

DROP INDEX onebv_idx;

SPOOL OFF