-- Assignment 2 Task 2
-- Timothy Mah
-- 8750634
-- txamah001@mymail.sim.edu.sg

SPOOL solution2Output.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE PROJECTGROUPS AS

CURSOR singlerow IS
SELECT PROJECT.P#, PROJECT.PTitle, LISTAGG(EMPLOYEE.NAME, ', ') WITHIN GROUP (ORDER BY EMPLOYEE.NAME) AS Employees 
FROM PROJECT 
JOIN EMPLOYEE ON PROJECT.D# = EMPLOYEE.D# 
JOIN WORKSON ON EMPLOYEE.E# = WORKSON.E#
GROUP BY PROJECT.P#, PROJECT.PTitle
ORDER BY PROJECT.P#;

BEGIN   
    for x in singlerow
    loop
        DBMS_OUTPUT.PUT_LINE(x.P# || ' ' || x.PTitle || ': ' || x.Employees);
    end loop;

END;
/

EXECUTE PROJECTGROUPS;

SPOOL OFF