-- Assignment 2 Task 3
-- Timothy Mah
-- 8750634
-- txamah001@mymail.sim.edu.sg

SPOOL solution3Output.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE FINDDEPENDENTS AS

CURSOR singlerow IS
SELECT EMPLOYEE.E#, EMPLOYEE.NAME, LISTAGG(DEPENDENT.DNAME, ', ') WITHIN GROUP (ORDER BY DEPENDENT.DNAME) AS deps 
FROM EMPLOYEE 
LEFT JOIN DEPENDENT ON EMPLOYEE.E# = DEPENDENT.E#
GROUP BY EMPLOYEE.E#, EMPLOYEE.NAME
ORDER BY EMPLOYEE.E#;

BEGIN   
    for x in singlerow
    loop
        DBMS_OUTPUT.PUT_LINE(x.E# || ' ' || x.NAME || ': ' || x.deps);
    end loop;

END;
/

EXECUTE FINDDEPENDENTS;

SPOOL OFF