-- Assignment 2 Task 1
-- Timothy Mah
-- 8750634
-- txamah001@mymail.sim.edu.sg

SPOOL solution1Output.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON


CREATE INDEX A2TASK1IDX1 ON ORDERS(O_CLERK, O_ORDERSTATUS);
CREATE INDEX A2TASK1IDX2 ON LINEITEM(L_ORDERKEY);

-- (i)
explain plan set STATEMENT_ID='i' for
SELECT O_CLERK FROM ORDERS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','i','SERIAL'));
-- (ii)
explain plan set STATEMENT_ID='ii' for
SELECT O_CLERK FROM ORDERS WHERE O_ORDERSTATUS='F';
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','ii','SERIAL'));
-- (iii)
explain plan set STATEMENT_ID='iii' for
SELECT O_CLERK, L_ORDERKEY FROM ORDERS JOIN LINEITEM ON ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','iii','SERIAL'));
-- (iv)
explain plan set STATEMENT_ID='iv' for
SELECT O_ORDERSTATUS FROM ORDERS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','iv','SERIAL'));
-- (v)
explain plan set STATEMENT_ID='v' for
SELECT O_ORDERSTATUS, COUNT(*) FROM ORDERS GROUP BY O_ORDERSTATUS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','v','SERIAL'));
-- (vi)
explain plan set STATEMENT_ID='vi' for
SELECT O_CLERK FROM ORDERS WHERE O_ORDERKEY NOT IN (SELECT L_ORDERKEY FROM LINEITEM);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','vi','SERIAL'));
-- (vii)
explain plan set STATEMENT_ID='vii' for
SELECT O_CLERK FROM ORDERS WHERE O_CLERK = (SELECT MAX(O_CLERK) FROM ORDERS);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','vii','SERIAL'));
-- (viii)
UPDATE ORDERS SET O_ORDERSTATUS = 'F' WHERE O_CLERK = 'Clerk#000000602';
-- (ix)
DELETE FROM ORDERS WHERE O_CLERK = 'Clerk#000000602';
-- (x)
explain plan set STATEMENT_ID='x' for
SELECT O_CLERK FROM ORDERS ORDER BY O_ORDERSTATUS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE','x','SERIAL'));

DROP INDEX A2TASK1IDX1;
DROP INDEX A2TASK1IDX2;


SPOOL OFF